//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetailsForMachines
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> StorageId { get; set; }
    
        public virtual DeliveryNote DeliveryNote { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
